### ISSUE TITLE
Помилка: Image size (107070106 pixels) exceeds limit of 89478485 pixels

### ISSUE THREAD

**Issue by a-vasyliev** [a-vasyliev/clock_img_maker#8]
/usr/local/lib/python3.6/site-packages/PIL/Image.py:2546: DecompressionBombWarning: Image size (107070106 pixels) exceeds limit of 89478485 pixels could be decompression bomb DOS attack.
  DecompressionBombWarning)

![442](https://user-images.githubusercontent.com/1255946/46464059-1687f780-c7ce-11e8-83be-ee63e04cb78e.png)

**Comment by mallhate** [comment]
Це попередження, а не помилка. Бібліотеці PIL щось не сподобався розмір файлу. Можливо файл був створений не по стандарту.

**Comment by mallhate** [comment]
взагалі це попередження про перевищення ліміту к-сті пікселів.
https://stackoverflow.com/questions/25705773/image-cropping-tool-python
якщо Ви довіряєте картинкам  які є у Вас наявності то можете не зважати на попередження такого характеру. 
також є можливість відключити це попередження

**Comment by a-vasyliev** [comment]
Виключ плз

--
Андрей

**Comment by mallhate** [comment]
виключив
