### ISSUE TITLE
Файл не знайдено, якщо в імені дизайну є пробіл перед .png

### ISSUE THREAD

**Issue by a-vasyliev** [a-vasyliev/clock_img_maker#9]

**Comment by mallhate** [comment]
можна детальніше скрін з трейсбеком ?

**Comment by mallhate** [comment]
підозріваю, що після створення папки з пробілом в кінці система сама його видаляє

**Comment by mallhate** [comment]
os.makedirs не може створити кінцеву директорію з пробілами в кінці. Виправив шлях до файлу з поправкою на відсутність пробілу в папці. commit c50cfc00ac96794b3f18c4ab15e309886ee9b39f
